import { Schema, model } from 'mongoose';
import { TPreviousWork } from './previousWork.interface';

const PreviousWorkSchema = new Schema<TPreviousWork>(
  {
    title: { type: String, required: true },
    slug: { type: String, required: true },
    metaTitle: { type: String, required: true },
    metaDescription: { type: String, required: true },
    category: { type: String, required: true },
    thumbnail: { type: String, required: true },
    liveUrl: { type: String, required: true },
    requirement: { type: String, required: true },
    timeTakenToDevelop: { type: String, required: true },
    database1: { type: String, required: true },
    database2: { type: String, required: true },
    database3: { type: String },
    database4: { type: String },
    database5: { type: String },
    database6: { type: String },
    frontendTech1: { type: String, required: true },
    frontendTech2: { type: String, required: true },
    frontendTech3: { type: String, required: true },
    frontendTech4: { type: String, required: true },
    frontendTech5: { type: String },
    frontendTech6: { type: String },
    backEndTech1: { type: String, required: true },
    backEndTech2: { type: String, required: true },
    backEndTech3: { type: String },
    backEndTech4: { type: String },
    backEndTech5: { type: String },
    backEndTech6: { type: String },
    websiteFeature1: { type: String, required: true },
    websiteFeature2: { type: String, required: true },
    websiteFeature3: { type: String, required: true },
    websiteFeature4: { type: String, required: true },
    websiteFeature5: { type: String, required: true },
    websiteFeature6: { type: String, required: true },
    websiteFeature7: { type: String, required: true },
    websiteFeature8: { type: String, required: true },
    websiteFeature9: { type: String, required: true },
    websiteFeature10: { type: String, required: true },
    websiteFeature11: { type: String, required: true },
    websiteFeature12: { type: String, required: true },
    websiteFeature13: { type: String, required: true },
    websiteFeature14: { type: String, required: true },
    websiteFeature15: { type: String, required: true },
    securityFeature1: { type: String, required: true },
    securityFeature2: { type: String, required: true },
    securityFeature3: { type: String, required: true },
    securityFeature4: { type: String, required: true },
    securityFeature5: { type: String, required: true },
    securityFeature6: { type: String, required: true },
    securityFeature7: { type: String, required: true },
    securityFeature8: { type: String, required: true },
  },
  {
    timestamps: true,
  },
);

export const PreviousWork = model<TPreviousWork>('PreviousWork', PreviousWorkSchema);
